name: Azure ML Deploy

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check out the code from your GitHub repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python environment
      with:
        python-version: '3.8'  # Define Python version

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash  # Install Azure CLI

    - name: Login to Azure
      uses: azure/login@v1  # Login to Azure
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  # Use your Azure service principal credentials stored in GitHub Secrets

    - name: Deploy Model
      run: |
        az ml model deploy --name my-endpoint \
                           --model-path model.pkl \  # Provide path to the model (ensure it's in your repo or specified location)
                           --environment-name environment.yml \  # Specify your environment file for dependencies
                           --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
                           --workspace-name ${{ secrets.AZURE_WORKSPACE_NAME }}  # Azure resource group and workspace from secrets
